import { useState } from "react";
import { motion } from "framer-motion";
import { 
  Accordion, 
  AccordionContent, 
  AccordionItem, 
  AccordionTrigger 
} from "@/components/ui/accordion";

export default function FAQ() {
  const faqs = [
    {
      question: "How does the 1.25% cash back work?",
      answer: "We charge the standard 2.5% commission on the buyer's side in Canada, but we give 1.25% back to you at closing. For example, on a $500,000 home purchase, you'd get $6,250 back. This cash back can be used towards your down payment, closing costs, or renovations - it's entirely up to you."
    },
    {
      question: "How accurate are Lumify's AI-powered appraisals from Realtor Canada data?",
      answer: "Our AI appraisals leverage data from millions of Canadian properties and local market variables, achieving an accuracy rate of 98% when compared to final sale prices. The system is specifically trained on Canadian real estate markets and continuously improves as it processes more transactions."
    },
    {
      question: "Are the AI-generated documents legally binding in Canada?",
      answer: "Yes, all documents generated by Lumify are compliant with Canadian real estate laws and binding. Our AI is trained on thousands of Canadian legal real estate documents and updated regularly to comply with provincial regulations. Most importantly, a senior licensed agent reviews all documents before they are submitted."
    },
    {
      question: "How does the senior agent review process work?",
      answer: "After our AI generates documents and offers, they are automatically routed to one of our experienced licensed agents who reviews everything for accuracy, compliance, and strategic negotiation positioning. This combines the speed of AI with the expertise of seasoned professionals to give you the best of both worlds."
    },
    {
      question: "How much time will I save using Lumify?",
      answer: "Our clients report saving an average of 15-20 hours throughout their home buying process. The AI handles routine communications, paperwork generation, market research, and scheduling, allowing you to focus on selecting the right property and making informed decisions."
    },
    {
      question: "Can I still work with a human agent if I want to?",
      answer: "Absolutely. While our AI handles the bulk of the process, our team of licensed real estate professionals is available via chat, email, or phone to answer questions and provide support throughout your transaction. You can schedule one-on-one consultations at any time."
    }
  ];

  return (
    <section id="faq" className="py-16 bg-gray-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div 
          className="text-center"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          viewport={{ once: true }}
        >
          <h2 className="text-3xl font-extrabold text-gray-900 sm:text-4xl">
            Frequently Asked Questions
          </h2>
          <p className="mt-4 max-w-2xl text-xl text-gray-500 mx-auto">
            Get answers to common questions about our AI-powered brokerage.
          </p>
        </motion.div>

        <motion.div 
          className="mt-12 space-y-6 max-w-3xl mx-auto"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.2 }}
          viewport={{ once: true }}
        >
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`} className="bg-white rounded-lg shadow-sm overflow-hidden mb-4">
                <AccordionTrigger className="px-6 py-4 text-left text-lg font-medium text-gray-900 hover:no-underline">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="px-6 pb-4 text-gray-600">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </motion.div>

        <motion.div
          className="mt-10 text-center"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.4 }}
          viewport={{ once: true }}
        >
          <p className="text-primary font-medium">
            Still have questions? <a href="#contact" className="underline">Contact us</a> and we'll be happy to help.
          </p>
        </motion.div>
      </div>
    </section>
  );
}
